name: flux_firebase
description: A Firebase package for FluxStore apps
publish_to: 'none'
version: 1.0.1+14

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fstore:
    path: ../../
  inspireui: 2.2.1

  # FIREBASE PACKAGES
  firebase_core: any
  firebase_analytics: any
  firebase_auth: any
  firebase_remote_config: any
  firebase_dynamic_links: any
  cloud_firestore: any
  firebase_remote_config_web: any

  firebase_messaging: any

  # OTHERS
  intl: any
  timeago: ^3.7.0
  flutter_local_notifications: 17.2.2
  share_plus: ^10.1.1
  provider: 6.1.2
  collection: any
  easy_debounce: 2.0.3
  jumping_dot: 0.0.6
  flutter_linkify: 6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  intl: 0.20.2
  vector_math: 2.2.0
  path: 1.9.1
  timeago: 3.7.0


